allowBuilds:
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true

overrides:
  fast-uri: '>=3.1.2'
  serialize-javascript: '>=7.0.5'
  postcss: '>=8.5.10'
  brace-expansion: '>=5.0.6'
  diff: '>=8.0.3'
  tmp: '>=0.2.4'
