title: "{{DISPLAY_NAME}}"
description: "{{DESCRIPTION}}"
baseurl: "/{{EXTENSION_NAME}}"
url: "{{SITE_URL}}"

repository: "{{PUBLISHER}}/{{EXTENSION_NAME}}"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - node_modules/
  - _site/

collections:
  services:
    output: true
    permalink: /services/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: default
